### PR TITLE
improvement: rework documentation

### PR DESCRIPTION
**Pull request by WesleyBryie**
Reworking the documentation to use Docusaurus and with updated information.

### CODE REVIEW

**Comment by WesleyBryie** [comment]
Almost there, next steps are the rest of the guides, branding, and polishing.

**Comment by WesleyBryie** [comment]
I'm probably gonna work on or finish this tomorrow because i should have more time to do things.

**Comment by WesleyBryie** [comment]
I'm going to go ahead and say that this is ready for reviewing. Lmk if there are any issues.

(cc: @nythepegasus @Spidy123222 )

**Review by SternXD — APPROVED** [review]
This looks all good 👍

**Pull request merged**
