### PR TITLE
Add After Install Tips

### PR DESCRIPTION
**Pull request by WesleyBryie**

### CODE REVIEW

**Comment by Spidy123222** [comment]
Wouldn't it be better to just tell them to refresh in the instructions than having it as a separately category for such tip if it could be important? We do plan on doing a refresh feature on first install on sidestore but directly telling people will be better and do a notice on why. Which would be to finish the install process and prevent expiring early.

**Comment by WesleyBryie** [comment]
> Wouldn't it be better to just tell them to refresh in the instructions than having it as a separate category for such tip if it could be important? We do plan on doing a refresh feature on first install on sidestore but directly telling people will be better and do a notice on why. Which would be to finish the install process and prevent expiring early.

You do raise a great point. If you want, I can change that for you.

**Comment by WesleyBryie** [comment]
@Spidy123222 I have updated the install.md, and removed after-install.md.

**Comment by Spidy123222** [comment]
lgtm

**Pull request merged**
