### PR TITLE
Update faq.mdx

### PR DESCRIPTION
**Pull request by neoarz**

### CODE REVIEW

**Comment by neoarz** [comment]
It should actually be "Make sure your pairing file's  extension ends with" idk how to edit a pr

**Comment by polymo1** [comment]
> It should actually be "Make sure your pairing file's extension ends with" idk how to edit a pr

Edit your branch

**Comment by neoarz** [comment]
done i fixed

**Review by polymo1 — APPROVED** [review]
lgtm

**Pull request merged**
