### PR TITLE
Create create-account.md

### PR DESCRIPTION
**Pull request by Macleykun**
this is only the file to list how to create an apple account the fastest and best way.
This doesn't explain the issue with the account locking up by not using a selfhosted/safe anisette server.

Also, i'm not sure how to integrate this doc into the list, idk if you wish to put this on top or below.

### CODE REVIEW

**Comment by Spidy123222** [comment]
To intergrated you add a header on top with information of the doc and you also add a number that others aren’t using to add to the drop-down menu that’s on top of page.

**Comment by Macleykun** [comment]
hows this?

**Comment by Macleykun** [comment]
@Spidy123222 is the pr ready to be merged? or do you have any other suggestion what you would like changed?

**Comment by Macleykun** [comment]
@Spidy123222 is this ready for merging?

**Comment by Macleykun** [comment]
@Swifticul whadda ya think? good to go :)
Thank you for your suggestions aswell! <3

**Comment by Spidy123222** [comment]
I would mention using methods that don’t require making like making an iCloud account. You can make one by adding an account in mail in settings. You would go into accounts and add account and click iCloud and then create an account. There’s also the iTunes method which doesn’t include 2fa I think.

**Comment by Macleykun** [comment]
> I would mention using methods that don’t require making like making an iCloud account. You can make one by adding an account in mail in settings. You would go into accounts and add account and click iCloud and then create an account. There’s also the iTunes method which doesn’t include 2fa I think. For iCloud accounts it does require them being logged into the device so adding them to mail is great for alts. Doesn’t work for with external email accounts like gmail.

there is a way to create a 2fa less account!???
i'll focus on trying this out using the settings app with icloud to create the apple id, for alts no mfa is better :)

**Comment by Spidy123222** [comment]
> > I would mention using methods that don’t require making like making an iCloud account. You can make one by adding an account in mail in settings. You would go into accounts and add account and click iCloud and then create an account. There’s also the iTunes method which doesn’t include 2fa I think. For iCloud accounts it does require them being logged into the device so adding them to mail is great for alts. Doesn’t work for with external email accounts like gmail.
> 
> 
> 
> there is a way to create a 2fa less account!???
> 
> i'll focus on trying this out using the settings app with icloud to create the apple id, for alts no mfa is better :)

No 2fa only works with iTunes to my knowledge.

**Comment by Macleykun** [comment]
Thank you for sharing that detail @Spidy123222 
For now, i only added the iTunes methode as i don't see the benefits of using the mail methode compared to visiting the apple website.
I'm really happy to know about the 2FA less methode, it makes sideloading a breeze when i have to start over again!

Any other things before we merge?

**Comment by Spidy123222** [comment]
> Thank you for sharing that detail @Spidy123222 
> 
> For now, i only added the iTunes methode as i don't see the benefits of using the mail methode compared to visiting the apple website.
> 
> I'm really happy to know about the 2FA less methode, it makes sideloading a breeze when i have to start over again!
> 
> 
> 
> Any other things before we merge?

I'm fine with merging but on mail side it automatically assigns the phone number and stuff which makes it a low effort process compared to site.

**Comment by Macleykun** [comment]
> > Thank you for sharing that detail @Spidy123222
> > For now, i only added the iTunes methode as i don't see the benefits of using the mail methode compared to visiting the apple website.
> > I'm really happy to know about the 2FA less methode, it makes sideloading a breeze when i have to start over again!
> > Any other things before we merge?
> 
> I'm fine with merging but on mail side it automatically assigns the phone number and stuff which makes it a low effort process compared to site.

i had to add my number to it, but i do see the account added to the list of accounts on my device and it also sees my ipad.
Found out i could also just create an icloud email (no other email else needed) which is also really neat! Will start working on this pr today/in a bit!

**Comment by Macleykun** [comment]
How's this?

**Comment by Macleykun** [comment]
Thx for the fix :) think it’s then good to go?

**Pull request merged**
