### PR TITLE
Rework Custom Anisette Server page with up-to-date info

### PR DESCRIPTION
**Pull request by owoellen**
blowing off the dust on this page

### CODE REVIEW

**Comment by polymo1** [comment]
Other than that, lgtm!

**Comment by owoellen** [comment]
just fixed it !!

**Comment by polymo1** [comment]
@owoellen Please look at the review, resolve that, then I will merge!

**Review by SternXD — APPROVED** [review]
lgtm

**Review by polymo1 — APPROVED** [review]
Lgtm

**Pull request merged**
