### PR TITLE
Updated Custom Anisette Server Guide

### PR DESCRIPTION
**Pull request by wuaht**
i was following this guide and i had troubles creating the render server, so i joined your server on the wiki. Somehow, it lead me to AltStore's discord server instead of yours so i changed that too. I saw another dude having the same problem as me so i just updated the guide

### CODE REVIEW

**Comment by Spidy123222** [comment]
I would add the detail on how to fork as some people might not know how. Other than that lgtm.

**Comment by silxl** [comment]
Access

**Comment by silxl** [comment]
Access

**Comment by Spidy123222** [comment]
We will be going with this one [LINK](https://github.com/SideStore/SideStore-Docs/pull/13) as it has similar changes and more. Thanks for the contribution though.

**Pull request closed without merging**
